framework:
    workflows:
        drive:
            type: 'state_machine'
            marking_store: { property: status }
            supports: [ App\Entity\Drive ]
            places: [ open, in_progress, finished, cancelled ]
            transitions:
                join: {
                    from: [open, in_progress, finished, cancelled],
                    to: open
                }
                leave: {
                    from: open,
                    to: open
                }
                start: {
                    from: open,
                    to: in_progress
                }
                finish: {
                    from: in_progress,
                    to: finished
                }
                cancel: {
                    from: [open],
                    to: cancelled
                }
